# Generated by Django 3.2 on 2022-07-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20220712_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Birden fazla seçim yapmak için te "CTRL" veya "COMMAND" tuşuna basılı tutun.', null=True, to='courses.Tag'),
        ),
    ]
